# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title: Daisy Zhu \n 祝 雨馨
tagline:          
description:      
url:              
baseurl:          /

author:
  name:           
  url:           

paginate:         5

# Custom vars
version:          3.0

github:
  repo:           https://github.com/dzhuyx
